{% set name = "pathsimanalysis" %}
{% set version = "1.2.0" %}

# set to minimally supported Python based on package
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pathsimanalysis-{{ version }}.tar.gz
  sha256: afd63ec143d2ab28a11c4c530f3f8132ed0aec447391f8345f4fe8e68be8ed08

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.9.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - mdanalysis >=2.0.0
    - scipy >=1.5.0
    - matplotlib-base >=1.5.1
    - numpy >=1.22.3

test:
  imports:
    - pathsimanalysis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Calculates the geometric similarity of molecular dynamics trajectories using path metrics such as the Hausdorff and Fréchet distances.
  home: https://github.com/MDAnalysis/PathSimAnalysis
  license: LGPL-2.1-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - IAlibay
    - lilyminium
    - orbeckst
