{% set name = "pathsimanalysis" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pathsimanalysis-{{ version }}.tar.gz
  sha256: fe43644916a47b7bbb0eaaba7ff4f3cd0e7e7a9389cb1fb3e6197f3275235b44

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9,<3.13
    - setuptools >=40.9.0
    - wheel
    - pip
  run:
    - python >=3.9,<3.13
    - mdanalysis >=2.0.0
    - scipy >=1.5.0
    - matplotlib-base >=1.5.1
    - numpy >=1.22.3

test:
  imports:
    - pathsimanalysis
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Calculates the geometric similarity of molecular dynamics trajectories using path metrics such as the Hausdorff and Fréchet distances.
  home: https://github.com/MDAnalysis/PathSimAnalysis
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - IAlibay
    - lilyminium
    - orbeckst
